### ISSUE TITLE
Setup documentation

### ISSUE THREAD

**Issue by OnlyC0RE** [snypy/snypy-docker#29]
Any plans to simplify the deployment?
I'm not a pro by any means but I'm no noobie either but the setup to deploy this app is very cumbersome and I'm not able to get it to work.

Why 2 compose files + .env? Why are there so many entries for domains and IPs and ports? There is literally no info about email setup. Why do I need to migrate db? What are fixtures and why do I want to load the setup.json? Why isn't in automatical?

What do I need to add to my Proxy manager? the app + api + static? no idea. I don't need anything else other then to be able to login through my snypy.domain.com and add snippets. I don't thing I need to work with rest api or anything else.

Sorry, I don't mean to sound ungrateful. I really dig the design and functionality. It's exactly und exactly what I'm looking for. And I (and 100% other users) would really love a simplified setup - or at least better documented to enjoy this really good looking app.

**Comment by OnlyC0RE** [comment]
sadge

**Comment by nezhar** [comment]
The setup process a a bit smoother now since https://github.com/snypy/snypy-docker/pull/33 and the `1.5.0` release.

We still need multiple compose files in order to extend the behavior, we may be able to also to this with environments.

The proxy is currently required to forward the traffic and manage ssl certificates. I'm thinking on adding an additional compose file that includes the proxy. This should make it easier to run the application on a local server.
